### ISSUE TITLE
Checksum mismatch error

### ISSUE THREAD

**Issue by atlanteh** [GitSquared/node-geolite2-redist#27]
We have another production issue. Checksum mismatch.
Can you please fix? Our instances crash.
Thanks!

**Comment by atlanteh** [comment]
Can you please let us know when you're starting to work on this. This is critical for us?

**Comment by GitSquared** [comment]
Can you confirm which version of the library you're on?

**Comment by atlanteh** [comment]
3.0.2

**Comment by GitSquared** [comment]
- just pushed an emergency update, should fix your builds
- paused the auto-updating process as it's causing too many issues recently. will take some downtime to investigate & make sure its fixed

Sorry for the recent interruptions.

**Comment by atlanteh** [comment]
Thanks a lot!

**Comment by GitSquared** [comment]
So the errors of the last few days where because MaxMind used to always update all databases at once and now they're sending out partial updates of only some databases at a time as well.

In #25 I fixed correctly writing partial db updates to the git repo, now I've just tweaked it so it makes separate commits and makes sure to always update the checksums. I think we should be good.

I've added a lot more debug logging and monitoring so I'll be keeping an eye on things in the next days. Don't hesitate to ping me if it happens again.

Thanks for your patience!

**Comment by atlanteh** [comment]
Thanks so much for the update.

**Comment by morpig** [comment]
hi, any db updates for this month?

**Comment by GitSquared** [comment]
@morpig thanks for pinging, the DBs have just been updated.
