### ISSUE TITLE
Support Node.js 10.x

### ISSUE THREAD

**Issue by AnandChowdhary** [GitSquared/node-geolite2-redist#6]
Hey @GitSquared, thanks for all your hard work with this package!

Is there a specific Node.js 12.x feature that's important for this, and is there any way we can support Node.js 10.x?

Issue context: https://github.com/staart/api/issues/1071

**Comment by GitSquared** [comment]
Hi Anand,
I'm sorry, I realized too late I should have bumped to a new major version with this compat change. My mistake.

I bumped to Node 12 because I used `{ recursive: true }` with `fs.rmdir()` which has been introduced in v12.10.

What prevents you from using only the latest LTS version of Node?

I'm aware v10 hasn't technically reached EOL yet so if you need it I'll add it back. However I'm currently on a tight deadline schedule @ work so it'd be helpful if you told me how critical that is for you. Otherwise I might have to delay this by ~2 weeks.

**Comment by AnandChowdhary** [comment]
Thanks for the swift reply!

My project @staart/api is dependent on `geolite2-redist`, and I want to make sure it works with all currently supported Node.js LTS versions. This was pointed out to me by @simoami in https://github.com/staart/api/issues/1071 which is why I opened this issue.

If you like, I can open a PR replacing `rmdir` with the `rmdir-recursive` package, which supports older Node versions as well. Otherwise, I'm happy to keep both issues open for a couple of weeks until we have that support, or alternately bump Staart API's minimum Node version to 12.x as well.

**Comment by simoami** [comment]
@GitSquared Thanks for the lib and for the prompt reply. Node 10 has just transitioned to maintenance LTS. However you will see in the following chart that it's is still prominent. It will be relevant to the broader user base.

![](https://nodejs.org/metrics/summaries/version.png)
Source: [nodejs.org](https://nodejs.org/metrics/)

**Comment by GitSquared** [comment]
I'm well aware of the usage share of v10, thank you. People still use windows XP too, doesn't mean I have to support it.
I'm open to PRs if you guys can't wait 2 weeks. As long as checks pass I can merge them immediately.

**Comment by AnandChowdhary** [comment]
Happy to wait. Thanks for your hard work! Stay safe!

**Comment by GitSquared** [comment]
You too.

**Comment by GitSquared** [comment]
@AnandChowdhary Thanks for your patience. `v1.0.6` has been released and published on NPM.
